import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/compoent/navbar/Navbar";
import Footer from "@/compoent/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Effort Estimation Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className=" bg-[rgb(103,51,154)] min-h-[100vh] w-[1000px] m-auto px-[50px] flex flex-col justify-between">
      <Navbar></Navbar>
      {children }
      <Footer></Footer>
      </div>
      </body>
    </html>
  );
}
